version: "3"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {WP_NAME}_wordpress
    volumes:
      - ./{WP_DIR}:/var/www/html
    ports:
      - {WP_PORT}:80
    links:
      - mysql
    restart: always

  mysql:
    image: mysql/mysql-server:latest
    container_name: {WP_NAME}_mysql
    ports:
      - {LOCAL_MYSQL_PORT}:3306
    expose:
      - {LOCAL_MYSQL_PORT}
    environment:
      MYSQL_DATABASE: {LOCAL_MYSQL_DATABASE}_local
      MYSQL_USER: {LOCAL_MYSQL_USERNAME}
      MYSQL_PASSWORD: {LOCAL_MYSQL_PASSWORD}
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: {WP_NAME}_phpmyadmin
    volumes:
      - /sessions
    ports:
      - {PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: {PHPMYADMIN_ARBITRARY}
      PMA_HOST: {PHPMYADMIN_MYSQL_HOST}
      PMA_PORT: {PHPMYADMIN_MYSQL_PORT}
    restart: always
