version: "3"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {WP_NAME}_wordpress
    volumes:
      - ./{WP_DIR}:/var/www/html
    ports:
      - {WP_PORT}:80
    restart: always

  mysql:
    image: mysql/mysql-server:latest
    container_name: {WP_NAME}_mysql
    ports:
      - {LOCAL_MYSQL_PORT}:3306
    environment:
      LOCALHOST: mysql
      MYSQL_DATABASE: {WP_NAME}
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: {LOCAL_MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/logs:/var/log/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: {WP_NAME}_phpmyadmin
    volumes:
      - /sessions
    ports:
      - {PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: {PHPMYADMIN_ARBITRARY}
      PMA_HOST: {PHPMYADMIN_MYSQL_HOST}
      PMA_PORT: {PHPMYADMIN_MYSQL_PORT}
    restart: always
