#!/bin/sh

source ./variables.sh

# Exit on file checkout, more: https://stackoverflow.com/questions/1011557/is-there-a-way-to-trigger-a-hook-after-a-new-branch-has-been-checked-out-in-git
if [ "$3" ] && [ "$3" == "0" ]; then
  exit
fi

# This file will get copied to .git/hooks and will execute upon branch checkout

IS_DEPLOYMENT=0

if [[ $# -eq 1 ]] ; then
  IS_DEPLOYMENT=$1
fi

readonly PUBLIC_WEB_DIR=$(jq -r ".publicWebDir" ./app.json)
readonly WP_NAME=$(jq -r ".docker.wordpress.name" ./app.json)
readonly CONNECT_LOCAL_MYSQL_FOR_DEV=$(jq -r ".connectLocalMysqlForDev" ./app.json)

if [ "$APP_BRANCH" == "dev" ] && [ "$CONNECT_LOCAL_MYSQL_FOR_DEV" -eq 1 ] && [ "$IS_DEPLOYMENT" -eq 0 ]; then
  #readonly PORT=$(jq -r ".docker.mysql.port" $APP_CONFIG_FILE)
  readonly HOST=mysql
  readonly DATABASE=${WP_NAME}_local
  readonly USER=$(jq -r ".docker.mysql.username" $APP_CONFIG_FILE)
  readonly PASSWORD=$(jq -r ".docker.mysql.password" $APP_CONFIG_FILE)
else
  readonly HOST=$(jq -r ".${APP_BRANCH}.endpoint" ./db.json)
  readonly DATABASE=$(jq -r ".${APP_BRANCH}.database" ./db.json)
  readonly USER=$(jq -r ".${APP_BRANCH}.user" ./db.json)
  readonly PASSWORD=$(jq -r ".${APP_BRANCH}.password" ./db.json)
fi

readonly WP_CONFIG_FILE=./${PUBLIC_WEB_DIR}/wp-config.php

# Create wp-config.php
cp ./${PUBLIC_WEB_DIR}/wp-config-default.php $WP_CONFIG_FILE

# Update wp-config.php
sed -i '' -e "s/define('DB_NAME', '.*');/define('DB_NAME', '$DATABASE');/g" $WP_CONFIG_FILE
sed -i '' -e "s/define('DB_USER', '.*');/define('DB_USER', '$USER');/g" $WP_CONFIG_FILE
sed -i '' -e "s/define('DB_PASSWORD', '.*');/define('DB_PASSWORD', '$PASSWORD');/g" $WP_CONFIG_FILE
sed -i '' -e "s/define('DB_HOST', '.*');/define('DB_HOST', '$HOST');/g" $WP_CONFIG_FILE
